spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/realms/hanyang}
          audiences:
            - ${KEYCLOAK_RESOURCE_CLIENT_ID:identity}

security:
  keycloak:
    resource-client-id: ${KEYCLOAK_RESOURCE_CLIENT_ID:identity}