IDENTITY_DB_NAME=identity_db
IDENTITY_DB_USER=identity_user
IDENTITY_DB_PASSWORD=identity_dev_password
IDENTITY_DB_PORT=25434

KEYCLOAK_DB_NAME=keycloak
KEYCLOAK_DB_USER=keycloak
KEYCLOAK_DB_PASSWORD=keycloak_dev_password

KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=admin
KEYCLOAK_PORT=18080

KEYCLOAK_URL=http://localhost:18080
KEYCLOAK_REALM=hanyang

KEYCLOAK_ADMIN_CLIENT_ID=identity-service-admin
KEYCLOAK_ADMIN_CLIENT_SECRET=l7hVq0oGLoNAavMrmD1uVpB5aTkaySLfpDLigItCPGRdpTUTGvNOfkfgfYaUh8zqgUeg4gDloGNv0HC30OIWMj

KEYCLOAK_ISSUER_URI=http://localhost:18080/realms/hanyang
KEYCLOAK_RESOURCE_CLIENT_ID=identity

SPRING_PROFILES_ACTIVE=keycloak



# Keycloak LDAP Federation (connection URL is from inside the Keycloak container)
KEYCLOAK_LDAP_FEDERATION_ENABLED=true
KEYCLOAK_LDAP_FEDERATION_NAME=hanyang-389ds
KEYCLOAK_LDAP_CONNECTION_URL=ldap://host.containers.internal:3389
KEYCLOAK_LDAP_EDIT_MODE=WRITABLE