spring:
  application:
    name: identity-service

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9080/realms/identity-development}

server:
  port: 8081
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true