spring:
  application:
    name: identity-service

  datasource:
    url: ${IDENTITY_DB_URL:jdbc:postgresql://localhost:5432/app_identity_service}
    username: ${IDENTITY_DB_USERNAME:app_identity_service}
    password: ${IDENTITY_DB_PASSWORD:StrongPassword123!}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration



  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9080/realms/identity-development}
          audiences:
            - ${KEYCLOAK_AUDIENCE:identity-api}

server:
  port: 8081
  shutdown: graceful

identity:
  keycloak:
    resource-client-id: ${KEYCLOAK_RESOURCE_CLIENT_ID:identity-api}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true